In [12]:
using DelimitedFiles
A, header = readdlm("/home/minhhn/Documents/ML/Dataset/Fuel/fuel.txt", ',', header=true)

(Any["AL" 3559897 … 3451586 18; "AK" 472211 … 457728 8; … ; "WI" 3667497 … 4156609 27.3; "WY" 370713 … 381882 14], AbstractString["State" "Drivers" … "Pop" "Tax"])

$$ 

(R'R)^{-1}R'y = x

$$

In [13]:
taxid = header[1,:] .== "Tax"
tax = Matrix{Float64}(A[:, taxid])

51×1 Matrix{Float64}:
 18.0
  8.0
 18.0
 21.7
 18.0
 22.0
 25.0
 23.0
 20.0
 13.6
  ⋮
 20.0
 20.0
 24.5
 20.0
 17.5
 23.0
 25.65
 27.3
 14.0

In [14]:
driverid = header[1,:] .== "Drivers"
popid = header[1,:] .== "Pop"
dlic = Matrix{Float64}(1000 .* A[:, driverid] ./ A[:, popid])

51×1 Matrix{Float64}:
 1031.3800670184662
 1031.6410619407159
  908.5971532882954
  946.5705758213509
  844.7033363249545
  989.6061797676718
  999.5934303166717
  924.3448380959871
  700.1952729018834
 1000.124158077562
    ⋮
  942.0443649520342
  835.2955548937877
  935.7885458586665
 1075.288201725559
  889.9195143953199
  930.8562455424127
  904.8936009399672
  882.3290812294349
  970.7527456125191

In [15]:

incomeid = header[1,:] .== "Income"
income = Matrix{Float64}( A[:, incomeid] )


51×1 Matrix{Float64}:
 23471.0
 30064.0
 25578.0
 22257.0
 32275.0
 32949.0
 40640.0
 31255.0
 37383.0
 28145.0
     ⋮
 26239.0
 27871.0
 23907.0
 26901.0
 31162.0
 31528.0
 21915.0
 28232.0
 27230.0

In [16]:
milesid = header[1,:] .== "Miles"
logMiles = Matrix{Float64}( log2.(A[:, milesid]) )

51×1 Matrix{Float64}:
 16.527110421116006
 13.734286232096347
 15.753556277508256
 16.58243604314262
 17.364707500812983
 16.389597731548893
 14.351905441476942
 12.505315356136236
 10.583082767502933
 16.839831188560346
  ⋮
 16.422360477832594
 18.198286758380327
 15.365228849251544
 13.802819250816214
 16.109851054234124
 16.305367097057776
 15.175120670274953
 16.781654267845337
 14.736190500960927

In [17]:
fuelcid = header[1,:] .== "FuelC"
fuel = Matrix{Float64}( 1000 .* A[:, fuelcid] ./ A[:, popid] )

51×1 Matrix{Float64}:
 690.2644175749931
 514.2792225950783
 621.475071439064
 655.2926679346258
 573.9128549539
 616.6115116683296
 549.9926078239395
 626.0239337079222
 317.492397161607
 586.3460960564428
   ⋮
 638.2310609545192
 681.100136591545
 591.4999458878183
 691.0227118608703
 681.0311214380635
 576.0697495580029
 562.4109333021843
 581.7937169457123
 842.7917524261421

In [18]:
N = length(A[:,1])
X = [ones(N) tax dlic income logMiles]

51×5 Matrix{Float64}:
 1.0  18.0   1031.38   23471.0  16.5271
 1.0   8.0   1031.64   30064.0  13.7343
 1.0  18.0    908.597  25578.0  15.7536
 1.0  21.7    946.571  22257.0  16.5824
 1.0  18.0    844.703  32275.0  17.3647
 1.0  22.0    989.606  32949.0  16.3896
 1.0  25.0    999.593  40640.0  14.3519
 1.0  23.0    924.345  31255.0  12.5053
 1.0  20.0    700.195  37383.0  10.5831
 1.0  13.6   1000.12   28145.0  16.8398
 ⋮                              
 1.0  20.0    942.044  26239.0  16.4224
 1.0  20.0    835.296  27871.0  18.1983
 1.0  24.5    935.789  23907.0  15.3652
 1.0  20.0   1075.29   26901.0  13.8028
 1.0  17.5    889.92   31162.0  16.1099
 1.0  23.0    930.856  31528.0  16.3054
 1.0  25.65   904.894  21915.0  15.1751
 1.0  27.3    882.329  28232.0  16.7817
 1.0  14.0    970.753  27230.0  14.7362

In [19]:
y = fuel

51×1 Matrix{Float64}:
 690.2644175749931
 514.2792225950783
 621.475071439064
 655.2926679346258
 573.9128549539
 616.6115116683296
 549.9926078239395
 626.0239337079222
 317.492397161607
 586.3460960564428
   ⋮
 638.2310609545192
 681.100136591545
 591.4999458878183
 691.0227118608703
 681.0311214380635
 576.0697495580029
 562.4109333021843
 581.7937169457123
 842.7917524261421

In [20]:
train(X, y) = inv(X'* X)* X'* y

train (generic function with 1 method)

In [21]:
predict(θ, xNew) = xNew * θ

predict (generic function with 1 method)

In [22]:
θ = train(X, y)

5×1 Matrix{Float64}:
 154.19284457730828
  -4.2279832083293485
   0.47187121344198957
  -0.006135330970417796
  18.545274506045644